coverage:
  status:
    project:
      default:
        target: 0%
        if_ci_failed: error
    patch:
      default:
        target: 0%
        if_ci_failed: error
# https://docs.codecov.com/docs/commit-status
